forced subs support
SRGSSR/nginx-vod-module pull request #3
Opened 2022-04-01 13:03 UTC by shugli

2022-04-01 15:11 UTC, SebastienChauvin requested changes

2022-04-01 15:11 UTC, SebastienChauvin commented on vod/hls/m3u8_builder.c
> +#define M3U8_EXT_MEDIA_NON_FORCED "FORCED=NO,"
Tu penses qu'on est obligé de mettre `FORCED=NO,` ?
On pourrait ne rien mettre dans le cas NO

2022-04-01 16:34 UTC, shugli commented on vod/hls/m3u8_builder.c
> +#define M3U8_EXT_MEDIA_NON_FORCED "FORCED=NO,"
je sais pas trop j'avoue! Vais creuser!

2022-04-02 21:22 UTC, shugli commented on vod/hls/m3u8_builder.c
> +#define M3U8_EXT_MEDIA_NON_FORCED "FORCED=NO,"
done

2022-04-05 07:08 UTC, SebastienChauvin approved these changes

2022-04-05 15:23 UTC, merged